### ISSUE TITLE
Redis session doesn't seem to be working

### ISSUE THREAD

**Issue by tusharsadhwani** [benawad/lireddit#10]
I'm following the tutorial and i'm about 4 hours in, and I notice that whenever i try to get the `me` query, my req.session never has a `userId` field.

I'm clearly setting `req.session.userId` everytime i login or register, and yet it doesn't get registered.

Here's a log showing `req.session` during login and inside me query:

```console
[query] select "e0".* from "post" as "e0" [took 4 ms]
[query] select "e0".* from "user" as "e0" where "e0"."username" = 'tushar' limit 1 [took 5 ms]
Login session:  Session {
  cookie: {
    path: '/',
    _expires: 2030-10-02T17:16:53.696Z,
    originalMaxAge: 315360000000,
    httpOnly: true,
    secure: false,
    sameSite: 'lax'
  },
  userId: 1
}
session:  Session {
  cookie: {
    path: '/',
    _expires: 2030-10-02T17:58:59.372Z,
    originalMaxAge: 315360000000,
    httpOnly: true,
    sameSite: 'lax',
    secure: false
  }
}
[query] select "e0".* from "post" as "e0" [took 6 ms]
```

My code is present here: https://github.com/tusharsadhwani/lireddit

**Comment by benawad** [comment]
I'm guessing the cookie is not getting correctly set when you login, double check https://benawad.com/cookie

**Comment by tusharsadhwani** [comment]
I wasnt setting the cookies in createUrqlClient, welp
