### ISSUE TITLE
Type 'ComponentWithAs<"textarea", TextareaProps>' is not assignable to type 'ComponentWithAs<"input", InputProps>'.

### ISSUE THREAD

**Issue by ahmedrowaihi** [benawad/lireddit#19]
![Code_QiWB3htvfu](https://user-images.githubusercontent.com/67356781/103482727-8cd39400-4df3-11eb-9d0b-453531ab6da3.png)

**Comment by benawad** [comment]
Probably not worth fighting the types here, I would cast it to any

```
InputOrTextarea = Textarea as any;
```
