### ISSUE TITLE
set session_replication_role = 'replica'; 

### ISSUE THREAD

**Issue by nenadSavovic1** [benawad/lireddit#2]
Hi @benawad , I am not sure if this is the right place to ask you this, but I got a bug and it is tricky to kill it.
I am on the 36th minute of the tutorial, I am trying to run the app, do the first migration, and insert the first post.

I am getting this error:  
![Screen Shot 2020-08-21 at 4 47 52 PM](https://user-images.githubusercontent.com/5949107/90903827-cb315f00-e3ce-11ea-989c-c31566692f22.png)

For some reason, it tries to execute select statement two times and just looks like a lot of funny business with the SQL.
Any ideas, thoughts?

**Comment by kurtzilla** [comment]
2 fixes I found. #1 is probably the most preferable
1) make sure the postgres user has superuser privileges - ALTER USER myuser WITH SUPERUSER;
2) in the mikro-orm.config, in the migrations section, add the disableForeignKeys option
export default {
  migrations: {
    path: path.join(__dirname, './migrations'),
    pattern: /^[\w-]+\d+\.[tj]s$/,
    disableForeignKeys: false,
  },
...

**Comment by nenadSavovic1** [comment]
@kurtzilla Looks like a clean and elegant solution, thanks for the info

**Comment by livike** [comment]
@kurtzilla Thanks! the #1 worked for me.
