### ISSUE TITLE
Error with connecting ioredis library

### ISSUE THREAD

**Issue by rrostyslav** [benawad/lireddit#23]
Hello Ben. Thanks for your Graphql TS video.
I repeat everything you do on it.
I catch an error when trying to replace redis library to ioredis.
Can you help me to resolve this problem please?

![image](https://user-images.githubusercontent.com/31695066/105643694-f9452e80-5e99-11eb-9084-df2da0953b80.png)
![image](https://user-images.githubusercontent.com/31695066/105643708-12e67600-5e9a-11eb-9dc6-89c7f444c6bf.png)

**Comment by rrostyslav** [comment]
<details>
<summary>Full error text:</summary>
Type 'Redis' is not assignable to type 'RedisClient | Redis | Cluster | undefined'.
  Type 'import("c:/Users/rrost/Documents/JS/train/graphql/node_modules/@types/ioredis/index").Redis' is not assignable to type 'import("c:/Users/rrost/Documents/JS/train/graphql/node_modules/@types/connect-redis/node_modules/@types/ioredis/index").Redis'.
    Types of property 'hset' are incompatible.
      Type 'OverloadedKeyedHashCommand<ValueType, number>' is not assignable to type 'OverloadedKeyedHashCommand<ValueType, "OK">'.
        Types of parameters 'cb' and 'cb' are incompatible.
          Types of parameters 'res' and 'res' are incompatible.
            Type 'number' is not assignable to type '"OK"'.ts(2322)
index.d.ts(28, 13): The expected type comes from property 'client' which is declared here on type 'RedisStoreOptions'
</details>

**Comment by Barklim** [comment]
@rrachinskiy Привет, нашел в чем проблема? У меня сейчас та же проблема.

**Comment by rrostyslav** [comment]
I using as any for now👌. I know this is bad idea

**Comment by baptistemcn** [comment]
Hey @rrachinskiy, can you send a screen with your context file maybe ? 👌🏻

**Comment by Barklim** [comment]
@baptistemcn

![photo_2021-01-30_21-00-10](https://user-images.githubusercontent.com/46284548/106411353-270c1380-6456-11eb-9be0-d7ee21bbffcf.jpg)

**Comment by rrostyslav** [comment]
It's seems like this issue has been fixed. Yesterday I tried to use express-session on my new pet project. I am not using GraphQL. It's simple REST API. Now it is working without any type. Check [here](https://github.com/rrachinskiy/session-auth) . 
Closing issue
