### ISSUE TITLE
How to set cookies using connect-mongo instead of connect-redis middleware

### ISSUE THREAD

**Issue by divakar54** [benawad/lireddit#25]
Hey Ben.
thanks a lot for the tutorial, I have been learning a lot from it.
I am running a windows machine and I couldn't  use redis on it. So, i used connect-mongo middleware with express-session. Issue is I can see them getting stored in database but can't see them in browser. They are not getting stored in browser.

![image](https://user-images.githubusercontent.com/38725511/106161436-00777f80-61ad-11eb-81d4-0d2697d0cf3e.png)

**Comment by rrostyslav** [comment]
Using MongoDB for storing sessions is btw bad idea. Mongo is too slow. Every single request sended to your server, will start reading from database. Redis has much higher reading speed then mongo.
Just download Redis for windows https://github.com/microsoftarchive/redis/releases/tag/win-3.0.504
and connect it exact as on the tutorial

**Comment by rrostyslav** [comment]
To start redis server, just run file redis-server.exe

**Comment by divakar54** [comment]
But the version of redis is 3.0 something, on their official site it's 6.0.10.

**Comment by rrostyslav** [comment]
Use linux, then

**Comment by herbievine** [comment]
I you want to use Redis on Windows, install it via Chocolatey. Then run Windows Powershell in admin mode and run `redis-server`. 

Some links: 
[Install Chocolatey](https://chocolatey.org/install)
[Install Redis](https://chocolatey.org/packages/redis-64)

![image](https://user-images.githubusercontent.com/41120535/110119949-55ae3e80-7db4-11eb-8395-cece12d6c432.png)

Hope this helps @divakar54
