### ISSUE TITLE
useMeQuery() doesn't run after redirection from login/register page

### ISSUE THREAD

**Issue by Sc1pex** [benawad/lireddit#54]
After redirecting from the login/register pages to the homepage, useMeQuery() does not run, it only runs after reloading from browser.

This is my navbar code:
```tsx
export const Navbar: React.FC<NavbarProps> = ({}) => {
  const [{ data, fetching }] = useMeQuery();
  let body = null;
  console.log(data);
  console.log(fetching);
  const router = useRouter();

  if (fetching) {
    // Data is loading
    body = null;
  } else if (!data?.me) {
    // Not logged in
    body = (
      <div className="ml-auto flex">
        <Link href="/login">
          <div className="mr-2 cursor-pointer hover:underline">Login</div>
        </Link>
        <Link href="/register">
          <div className="cursor-pointer hover:underline">Register</div>
        </Link>
      </div>
    );
  } else {
    // Logged in
    body = <div className="ml-auto">Hello, {data.me.username}</div>;
  }

  return <div className="flex bg-gray-500 p-4">{body}</div>;
};
```

Not sure if it matters, but I am using router.push to redirect. I've tried router.replace but that won't work either.

Thanks!

**Comment by Sc1pex** [comment]
Also this is the console output:
![Untitled](https://user-images.githubusercontent.com/92252113/155896505-039fce5d-47cc-45ea-8749-3aa68add3106.png)

**Comment by Sc1pex** [comment]
Nvm, I should have just kept watching

**Comment by lightify97** [comment]
@Sc1pex How did you solve it? I'm experiencing the same.

**Comment by Sc1pex** [comment]
@lightify97 it’s solved in the video in the next 5-10 minutes I think
