### ISSUE TITLE
createUrqlClient url not in force

### ISSUE THREAD

**Issue by caicaishmily** [benawad/lireddit#6]
I just follow your tutorials，I set the `url: "http://localhost:4000/graphql"`,  but the browser can't found the server. here is my `createUrqlClient.js` snippet, Is there any setting to add ?

```js
export const createUrqlClient = (ssrExchange: any) => ({
  url: "http://localhost:4000/graphql",
  fetchOptions: {
    credentials: "include" as const,
  },
  exchanges: [
    dedupExchange,
    cacheExchange({
      ... 
    }),
    ssrExchange,
    fetchExchange,
  ],
});
```

![image](https://user-images.githubusercontent.com/19269210/92626776-f7207000-f2fc-11ea-81ee-8402dbfb4dad.png)

**Comment by benawad** [comment]
from your screenshot it looks like it is making a request to `localhost:3000` not `localhost:4000`

**Comment by caicaishmily** [comment]
> from your screenshot it looks like it is making a request to `localhost:3000` not `localhost:4000`

Yes, But what make me feel confused is that I set the request url is `localhost:4000`. However, it request for `localhost:3000`. So weird.

**Comment by caicaishmily** [comment]
> from your screenshot it looks like it is making a request to `localhost:3000` not `localhost:4000`

I cloned your repo then compare it with my code.  I found the only difference between our code is the `package.json` file.  
Then I copied your package.json and `rm -rf node_modules && yarn install`, 
It worked. 
Maybe it's caused by the dependency version.
Anyway, Thx a lot! @benawad

**Comment by voland62** [comment]
Got the same problem. This is iteresting.. Nothing helped, even caicaishmily's method...
It says: 

> Default Client: No client has been specified using urql's Provider.This means that urql will be falling back to defaults including making requests to `/graphql`.
If that's not what you want, please create a client and add a Provider.

But, then I found, if we replace yarn.lock from ben's repo(branch 15_urql-ssr in our case), all works after /node_modules refresh!...

**Comment by wandingistaken** [comment]
The same error happened to me logging because I forgot to wrap my `login` page with `createUrqlClient`
`export default withUrqlClient(createUrqlClient)(Login);`
