### ISSUE TITLE
No client has been specified using urql's Provider

### ISSUE THREAD

**Issue by noxevolution** [benawad/lireddit#7]
Hello Ben, I am a newbie to react and after creating **createUrqlClient.ts** file and copy the `cacheExcange` from **_app.tsx**, then removing all the unnecessary imports from **_app.tsx** and exporting the index like this `export default withUrqlClient(createUrqlClient)(Index)` in **index.tsx** file, I am getting the error below,

```
Default Client: No client has been specified using urql's Provider.This means that urql will be falling back to defaults including making requests to `/
graphql`.
If that's not what you want, please create a client and add a Provider.
```
How can i solve this issue?

**Comment by benawad** [comment]
Did you see https://github.com/benawad/lireddit/issues/6

**Comment by noxevolution** [comment]
Thx a lot! @benawad . solved it through voland62's comment.
